### PR TITLE
Issue #1: Output file name pattern shouldn't require '%s' 

### PR DESCRIPTION
**Pull request by israeldago**
Hello,
This PR should fix this issue + README.md update
I also observed that there were no assertions for the the issuerCards, so i added one assertion line in CreditCardGeneratorTests for that.
Thank you in advance :)
@israeldago

### CODE REVIEW

**Review by xcapdevila — CHANGES_REQUESTED** [review]
Excellent @israeldago !!

Just a few easy changes to do.

Required:
- Delete CreditCardGeneratorTests line 37 comment
- Update pom version to 1.1

Optional:
- Extract "${now}" placeholder to a constant

Thank you!!

**Comment by israeldago** [comment]
Helle @xcapdevila,
Thx for your feedback.
Regarding *"Delete CreditCardGeneratorTests line 37 comment"* -> i think you are refering about the line 35 instead for the current issue. Isn't it ?

**Review by xcapdevila — APPROVED** [review]

**Comment by xcapdevila** [comment]
Many thanks @israeldago

**Comment by israeldago** [comment]
Thx @xcapdevila, 
Actually it was very fun, have a nice day :)

**Pull request merged**
